###########
# ENV VARS:
# - DOCKER_USERNAME
# - DOCKER_PASSWORD
# - GITHUB_TOKEN (default)
###########

name: Docker Image CI

on:
  push:
    paths:
      - 'release-versions/*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Get current repository
        uses: actions/checkout@v4
      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(cat release-versions/n8n-latest.txt)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
# n8n
      - run: cp default-requirements.txt images/n8n-zh/requirements.txt
      - name: Build (default => alpine)
        uses: docker/build-push-action@v6
        with:
          context: ./images/n8n-zh
          build-args: |
            N8N_VERSION=${{steps.vars.outputs.tag}}
          platforms: linux/amd64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/n8n-python-zh:${{ steps.vars.outputs.tag }}
            ${{ secrets.DOCKER_USERNAME }}/n8n-python-zh:latest
#n8n-debian
      - run: cp default-requirements.txt images/n8n-debian-zh/requirements.txt
      - name: Build (debian)
        uses: docker/build-push-action@v6
        with:
          context: ./images/n8n-debian-zh
          build-args: |
            N8N_VERSION=${{ steps.vars.outputs.tag }}
          platforms: linux/amd64
          #,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/n8n-python-zh:${{ steps.vars.outputs.tag }}-debian
            ${{ secrets.DOCKER_USERNAME }}/n8n-python-zh:latest-debian

      - name: Docker Hub Description (README.md)
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: jnukylin/n8n-python-zh
          readme-filepath: README.md

      - name: Create Release in GitHub
        id: create_release
        uses: actions/create-release@v1
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v${{steps.vars.outputs.tag}}
          release_name: Release ${{steps.vars.outputs.tag}}
          body: n8n v${{steps.vars.outputs.tag}} (python3 included)
